### PR TITLE
Prometheus Metrics

### PR DESCRIPTION
**Pull request by Philip-21**
Pr fixes for #34 

Creating prometheus instrumentation for FFEVM

### CODE REVIEW

**Review by Chengxuan — CHANGES_REQUESTED** [review]
@Philip-21 thanks for looking at adding the metrics!

 Instead of using the prometheus library directly, there is a standard util in firefly-common which can help organise metrics when it grows bigger. An example usage can be found here: https://github.com/hyperledger/firefly-transaction-manager/blob/main/internal/metrics/metrics.go

**Comment by Philip-21** [comment]
> @Philip-21 thanks for looking at adding the metrics!
> 
> Instead of using the prometheus library directly, there is a standard util in firefly-common which can help organise metrics when it grows bigger. An example usage can be found here: https://github.com/hyperledger/firefly-transaction-manager/blob/main/internal/metrics/metrics.go

Thanks for the feedback, i just cloned the repo and i am looking into it

**Comment by Philip-21** [comment]
Hey @Chengxuan  please checkout the changes I have made, I  made necessary adjustments for handling the metrics, my main issue is being able to configure the metrics server to run properly, I need your reviews on this please ? 
I hope I'm doing the right thing👀

**Comment by Chengxuan** [comment]
@Philip-21 Thanks for the update. I realised what I explained above wasn't very clear. 

FFTM already has a metrics manager and I believe that metrics manager is the one that EVM connect should use for collecting metrics so that the custom metrics collected in EVM connect are served at the same metrics server as other metrics.


https://github.com/hyperledger/firefly-evmconnect/blob/main/cmd/evmconnect.go#L102 is where EVM connect uses FFTM to initialize the HTTP & metrics server. 

There is already an example showing how Tx Handler registers and emits its custom metrics in https://github.com/hyperledger/firefly-transaction-manager/blob/main/internal/metrics/metrics.go through `txHandlerMetricsManager`.

Therefore, EVM connect could follow the same pattern. e.g. there can be a new `evmMetricsManager`, and a new interface 
similar to https://github.com/hyperledger/firefly-transaction-manager/blob/main/pkg/txhandler/txhandler.go#L76

**Comment by Philip-21** [comment]
Hey @Chengxuan I have created Evm handlers for handling  and emitting metrics, Please have a look on how i defined them and configured them to run and initialize in the `evmconnect.go`  file

**Comment by Chengxuan** [comment]
Hi @Philip-21 , Thanks for giving it another try.

The `MetricsRegistry` that is [hooked up](https://github.com/hyperledger/firefly-transaction-manager/blob/main/pkg/fftm/api.go#L35) with the API server (which is defined in FFTM code) is created in here: https://github.com/hyperledger/firefly-transaction-manager/blob/main/internal/metrics/metrics.go#L47.

Therefore, as a consumer of that library, FF evmconnect need to find a way to emit metrics using a `MetricsManager` that belongs to the `MetricsRegistry` [defined in FFTM code](https://github.com/hyperledger/firefly-transaction-manager/blob/main/internal/metrics/metrics.go#L47.).

In this PR, a new `MetricsRegistry` is created [here](https://github.com/hyperledger/firefly-evmconnect/pull/113/files#diff-6e56d7c057f6a96124b78f2b669dd7dface2718c304aece205017d114b3a7088R35) but it's not hooked up with any API that is defined in FFTM code, so the collected metrics will be in an isolated registry and won't be exposed to any REST API endpoint.

**Comment by Philip-21** [comment]
> Hi @Philip-21 , Thanks for giving it another try.
> 
> The `MetricsRegistry` that is [hooked up](https://github.com/hyperledger/firefly-transaction-manager/blob/main/pkg/fftm/api.go#L35) with the API server (which is defined in FFTM code) is created in here: https://github.com/hyperledger/firefly-transaction-manager/blob/main/internal/metrics/metrics.go#L47.
> 
> Therefore, as a consumer of that library, FF evmconnect need to find a way to emit metrics using a `MetricsManager` that belongs to the `MetricsRegistry` [defined in FFTM code](https://github.com/hyperledger/firefly-transaction-manager/blob/main/internal/metrics/metrics.go#L47.).
> 
> In this PR, a new `MetricsRegistry` is created [here](https://github.com/hyperledger/firefly-evmconnect/pull/113/files#diff-6e56d7c057f6a96124b78f2b669dd7dface2718c304aece205017d114b3a7088R35) but it's not hooked up with any API that is defined in FFTM code, so the collected metrics will be in an isolated registry and won't be exposed to any REST API endpoint.

Thanks for the feedback, i will make adjustments

**Comment by Philip-21** [comment]
I've ben unable to import the metrics registry from the fftm to be used for the Evmmetrics manager, since the metric registry for the fftm is located in the internal package i am unable to import and use it, leads to an import error , i am still figuring out a better approach to this

**Comment by Chengxuan** [comment]
@Philip-21 one option is to use a public interface and implement the internal object with the required methods then pass through it to evmconnect during initialization. But other proposals are welcome as well.

You might want to take a look at https://github.com/hyperledger/firefly-transaction-manager/blob/543a25094959495265d042083db8120169fcecf2/pkg/txhandler/txhandler.go#L76 , I feel that interface is generic enough to be re-used as it doesn't contain transaction handler specific knowledge.

**Comment by Philip-21** [comment]
Hey @Chengxuan , I think  its best we use the `txhandler.TransactionMetrics`, for handling various prometheus metrics methods. instead of creating `EvmTransactionHandlerMetrics`. 

But does `txhandler.TransactionMetrics` have a way of swapping signature contents which will  initialize the Prometheus Api instance defined in FFTM code.

**Comment by Chengxuan** [comment]
Hi @Philip-21 here is an example of adding event metrics in FFTM repo: https://github.com/hyperledger/firefly-transaction-manager/pull/121 which could be a useful learning point for adding metrics for EVM connect.

**Comment by Philip-21** [comment]
> Hi @Philip-21 here is an example of adding event metrics in FFTM repo: [hyperledger/firefly-transaction-manager#121](https://github.com/hyperledger/firefly-transaction-manager/pull/121) which could be a useful learning point for adding metrics for EVM connect.

Alright looking through ........

**Comment by Chengxuan** [comment]
Closing this PR for now as it seems the work has been parked. Please feel free to re-open when you continue @Philip-21 👍

**Pull request closed without merging**
